name: Build Windows application
description: Builds exe for Windows

inputs:
  buildType:
    description: Whether to build release, firebase or profile version. "release" for release version, "profile" for firebase version.
    required: true
  ENVIRONMENT_CONFIG_PRODUCTION:
    description: '.env and firebase files config file, bas64-encoded'
    required: true

runs:
  using: composite
  steps:
    - name: Prepare environment
      uses: ./.github/actions/prepare

    - name: Extract config
      run: |
        echo $ENVIRONMENT_CONFIG_PRODUCTION | base64 -d > config.zip
        make extract_config
      shell: bash
      env:
        ENVIRONMENT_CONFIG_PRODUCTION: ${{ inputs.ENVIRONMENT_CONFIG_PRODUCTION }}

    - name: Build release windows
      if: ${{ inputs.buildType == 'release' }}
      working-directory: packages/picnic-desktop-app
      run: |
        flutter build windows --release --build-number ${{ github.run_number }}
      shell: bash
      env:
        VERBOSE_SCRIPT_LOGGING: "true"

    - name: Build profile windows
      if: ${{ inputs.buildType == 'profile' }}
      working-directory: packages/picnic-desktop-app
      run: |
        flutter build windows --profile --build-number ${{ github.run_number }} --dart-define="BUILD_SOURCE_NAME=${BUILD_SOURCE_NAME}" --dart-define="BUILD_SOURCE_BRANCH=${BUILD_SOURCE_BRANCH}" --dart-define="BUILD_SOURCE_COMMIT=${BUILD_SOURCE_COMMIT}"
      shell: bash
      env:
        VERBOSE_SCRIPT_LOGGING: "true"

    - name: Create zip archive
      id: zip
      uses: vimtor/action-zip@v1.1
      with:
        files: packages/picnic-desktop-app/build/windows/runner/${{ inputs.buildType }}/
        dest: picnic-app-windows.zip

outputs:
  zip-path:
    description: "Path of built zip archive"
    value: "picnic-app-windows.zip"
