name: Validate README.md

on:
  pull_request:
    branches:
      - main
      - develop
      - "release/**"
      - 'feature/GS-[0-9]+/**'

    paths:
      - README.md
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    timeout-minutes: 2
    runs-on:
      - ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Lint README.md
        uses: avto-dev/markdown-lint@v1
        with:
          args: README.md
